[FEATURE] introducing wave info to expansion
on3iro/aeons-end-randomizer pull request #500
Opened 2023-03-17 16:01 UTC by MilanTheHawk

Issue: #467

Phase 2:
 - Sort expansions by wave in Settings -> Expansions
 - Display expansion/wave language dependent in Randomizer -> Nemesis
 - Display expansion/wave language dependent in Randomizer -> Nemesis Cards
 - Display expansion/wave language dependent in Randomizer -> Mages
 - Display expansion/wave language dependent in Nemesis details
 - Display expansion/wave language dependent in Nemesis Card details
 - Display expansion/wave language dependent in Mage details

2023-03-24 20:39 UTC, on3iro commented
@MilanTheHawk Just a quick heads up again that I haven't forgotten this PR - I am just really busy right now. But I am confident, that I'll get to it over the next couple of days :)

2023-03-25 08:25 UTC, on3iro requested changes
@MilanTheHawk Thanks a ton for your work ❤️ . There are a few minor changes I would like you to make. When these are done we can merge this :)

2023-03-25 08:25 UTC, on3iro commented on src/Redux/Store/Settings/Expansions/Expansions/index.ts
> +    let expansions: types.Expansion[]
These `let` bindings seem a bit unnecessary (as well as the type annotation)

Could you please change this to

```ts
    const expansions = ids.map((id) =>
      getContentWithLanguageFallback(languages, content, id)
    )
    return sortExpansions(expansions)
```

2023-03-25 08:25 UTC, on3iro commented on src/Redux/Store/Settings/Expansions/Expansions/index.ts
> +  (content, ids, languages) => {
Please see above :)

2023-03-25 08:25 UTC, on3iro commented on src/Redux/Store/Settings/Expansions/Expansions/index.ts
> +  (content, ids, languages) => {
please see above :)

2023-03-25 08:25 UTC, on3iro commented on src/aer-types/types/data.ts
> +    ? expansion.name + ' (' + expansion.wave + ')'
Could you please use a template literal instead of the manual concatenation here:

```ts
`${expansion.name} (${expansion.wave})`
```

2023-03-25 08:25 UTC, on3iro commented on src/aer-types/types/data.ts
> +    : expansion.name + ' (-)'
same as above :)

2023-03-25 08:25 UTC, on3iro commented on src/aer-types/types/data.ts
> +export function formatExpansionName(expansion: Expansion): string {
could you please move this out of the types package. A better place for this function would be `src/helpers/index.ts` :)

2023-03-25 11:22 UTC, MilanTheHawk commented
@on3iro Small changes are done :-)

2023-03-25 13:06 UTC, on3iro approved these changes
Awesome, thanks for applying these changes!

2023-03-25 13:07 UTC, merged