Wave 8 - The Caverns
on3iro/aeons-end-randomizer pull request #526
Opened 2024-12-02 02:41 UTC by deusabianca

This only includes one of the wave 8 mini expansions so far as I'm trying to figure out if this is the correct way to add content without issues.

2024-12-03 03:30 UTC, Torgen requested changes

2024-12-03 03:30 UTC, Torgen commented on src/aer-data/src/ENG/theCaverns/cards.ts
> +    keywords: ['develop'],
Add 'attach' keyword.

2024-12-03 03:30 UTC, Torgen commented on src/aer-data/src/ENG/theCaverns/cards.ts
> +    keywords: ['develop', 'elementaltoken'],
Add 'attach' keyword.

2024-12-03 03:30 UTC, Torgen commented on src/aer-data/src/ENG/theCaverns/cards.ts
> +    keywords: [''],
Delete empty string keyword.

2024-12-03 03:30 UTC, Torgen commented on src/aer-data/src/ENG/theCaverns/cards.ts
> +    keywords: [''],
Delete empty string keyword.

2024-12-03 03:30 UTC, Torgen commented on src/aer-data/src/ENG/theCaverns/cards.ts
> +    keywords: [''],
Delete empty string keyword.

2024-12-03 05:42 UTC, deusabianca commented
Thanks @Torgen - FYI I also changed 'elementaltoken' to 'elemental token'

2024-12-03 07:41 UTC, Torgen commented
FYI, am pretty close to having the Descent data entered, including friends and foes. Will probably make that a single PR, then a separate one for the code changes to make the friends and foes selectable in settings and allow picking them at random.

2024-12-03 08:00 UTC, Torgen commented on src/aer-data/src/ENG/talesOfOldGravehold/nemeses.ts
Is this nemesis in both expansions?

2024-12-03 08:02 UTC, deusabianca commented on src/aer-data/src/ENG/talesOfOldGravehold/nemeses.ts
Whoops, I meant to make this a nemesis file without any nemeses as the ruins and buried secrets folder has and see if that fixed the tests.

2024-12-03 08:11 UTC, deusabianca commented
> FYI, am pretty close to having the Descent data entered, including friends and foes.

Awesome ty @Torgen. I can work on the promos and The Abyss, though you could add the friends and foes from The Caverns and The Abyss?

2024-12-03 09:09 UTC, Torgen commented
Option 1 is if my PR gets merged first, you rebase so you can see the type changes that add friends and foes, then I do a PR into your branch to add them. Option 2 is you clone this PR into one against my branch and we end up with one big PR.

2024-12-03 21:44 UTC, deusabianca commented
All content from the minis aside from friends and foes and banners should be in this PR now.

@Torgen option 1 sounds good

2024-12-04 02:50 UTC, Torgen commented
There are no friends, foes, or banners in TOG, right? We didn't get that one.

2024-12-04 04:01 UTC, deusabianca commented
TOG only has 2 supply cards and a mage

2024-12-04 20:10 UTC, Torgen commented on src/aer-data/src/ENG/theCaverns/foes.ts
> +        cost: 0
Needs comma.

2024-12-04 20:23 UTC, Torgen requested changes

2024-12-04 20:23 UTC, Torgen commented on src/aer-data/src/ENG/theCaverns/foes.ts
> +        name: 'Fratctalize',
Has an extra t.

2024-12-04 20:23 UTC, Torgen commented on src/aer-data/src/ENG/theCaverns/friends.ts
> +    id: 'JoannatheMerchant',
Other friends have a capital T on their The in the id.

2024-12-04 20:23 UTC, Torgen commented on src/aer-data/src/ENG/theCaverns/friends.ts
> +
These are HTML. You need at least a `<br/>` to force these onto separate lines; a `</p><p>` will put a margin between them like it is on the card.

2024-12-04 20:23 UTC, Torgen commented on src/aer-data/src/ENG/theCaverns/banners.ts
> +	  you do, the friend gains 1 charge.
Needs a `<br/>` to put the Cast on a new line.

2024-12-04 22:58 UTC, Torgen commented on src/aer-data/src/ENG/TDPromos/cards.ts
> +    cost: 4,
Costs 6, doesn't develop.

2024-12-04 22:59 UTC, Torgen commented on src/aer-data/src/ENG/theAbyss/cards.ts
> +	developCost: 2,
Doesn't develop.

2024-12-06 06:22 UTC, on3iro commented
Hey @deusabianca is this ready for a final review and merge?

2024-12-06 07:51 UTC, deusabianca commented
@on3iro Yes should be good to go!

2024-12-07 13:05 UTC, on3iro submitted a review, later dismissed

2024-12-07 13:40 UTC, on3iro commented
@deusabianca thanks for the PR. Could you please do the following:

1. Squash all commits into a single one
2. Make sure to rebase the the current main branch into your branch and resolve all conflicts
3. Force push onto this branch again, to update the pr$

(I would've done this myself, however it seems you are probably using windows and your line endings are not configured properly. I tried to fix this quickly on my local machine, but didn't quite get it right and I am really short on time right now. I thought our `.gitattributes` file should've handled this already, but it seems that it's not yet configured properly....)

2024-12-08 03:57 UTC, deusabianca commented
I am still very much a noob with Github so the best way I found to do that I made a new pull request. I hope that's fine and we can close this one.

2024-12-08 11:10 UTC, on3iro commented
Sure no - problem :) thanks @deusabianca

2024-12-08 11:10 UTC, closed without merging